name: DeathPenalty
version: ${project.version}
main: net.icarey.deathpenalty.DeathPenalty
depend: [Vault]
authors: [Smashedbotatos]
description: In-game currency penalties for dying in minecraft.
api-version: 1.13
commands:
  deathpenalty:
    description: Main Command for DeathPenalties!
    aliases: [dp]